### ISSUE TITLE
Installing on OpenWrt(LEDE)

### ISSUE THREAD

**Issue by Nic2012** [bitbank2/oled_96#1]
Try to install the latest router OS OpenWrt/LEDE 17.04.1 on a Pi3, gaves me some errors because of the structure of OpenWrt, in makefile and make_sample:
in line 3
```
CFLAGS=-mfloat-abi=hard -c -Wall -O2
```
Otherwise I get the error "...uses VFP register arguments" during compile.
line 8 and 9:
```
sudo cp liboled96.a /usr/lib ;\
sudo cp oled96.h /usr/include
```
After these changes it works fine. But I have to start the sample executable with the interpreter like
```
/lib/ld-musl-armhf.so.1 --library-path /lib ./sample
```
So its not a big issue. Just inform y and others could run into the same.
BTW I would like to thank you for y effort to publish this stuff, it helps me in Pi programming a lot.

Best regards,
Nic

**Comment by bitbank2** [comment]
Not sure how to respond to this. Thanks for indicating the issue. It's odd that the gcc for OpenWRT wouldn't default to use reasonable options without having to be told. The code doesn't use any floating point math. The placement of the library into the 'local' section of /usr is another interesting difference.
