### ISSUE TITLE
syntax examples

### ISSUE THREAD

**Issue by BETLOG** [bitbank2/oled_96#2]
Can you provide command and syntax examples for this?
The 'compact library' part is appealing, but needing to pick through the source to figure out how to use it is tedious. Or are there examples aside from https://github.com/bitbank2/oled_96/blob/master/sample.c that aren't linked here?

**Comment by bitbank2** [comment]
Are you targeting Arduino or Linux? The .H file has the function prototypes and comments for how they're used. The sample.c shows how to get things going. There really isn't much to it. The value of this code is that it has all of the 'magic numbers' to get the display initialized and some efficient code for drawing fixed sized fonts.
