### ISSUE TITLE
Wrong channel in sample.c (Failed to open i2c bus)

### ISSUE THREAD

**Issue by Dak0r** [bitbank2/oled_96#3]
Hey, thanks for sharing your library.
I just cloned it and wanted to give it a try, but I couldn't get it working at frist.

Before I spend any more time, I wanted to compile and test the example, so simply builded and ran it, without looking to closely at the other files. Unfortunately I kept getting "Failed to open i2c bus".

I thought it was a permission issue, but could not resolve it. Only later I saw that _oledinit_'s first parameter is the channel, which is set to 0 in the example, eventhough the comment netxt to it says the call opens the bus on channel 1.

You might want to adjust that line from

`i=oledInit(0, 0x3c, 0, 0); // for Raspberry Pi, use channel 1`

`i=oledInit(1, 0x3c, 0, 0); // for Raspberry Pi, use channel 1`

Best regards
Daniel

**Comment by bitbank2** [comment]
Thanks for the heads up. I constantly switch back and forth between using RPI boards and other ARM boards (which usually use I2C0). Maybe I'll add an extra comment to the error message stating that you should double check which I2C channel you're using.
