### ISSUE TITLE
how to run it

### ISSUE THREAD

**Issue by kuzmanzs** [bitbank2/oled_96#4]
Hi,

I have tried to run it from Ubuntu but I got:
-bash: ./sample: cannot execute binary file: Exec format error

before:
make
make sample
+x to sample
./sample

uname -m
returns: x86_64

file sample
returns: sample: ELF 64-bit LSB relocatable, x86-64, version 1 (SYSV), not stripped

**Comment by bitbank2** [comment]
You've asked the system to create an empty file called "sample" in your actions above.

The correct procedure is:
make
make -f make_sample
sudo ./sample

**Comment by kuzmanzs** [comment]
thanks :)
