### ISSUE TITLE
 unvanted pixels are on the display

### ISSUE THREAD

**Issue by kuzmanzs** [bitbank2/oled_96#5]
Hi,

do you have any idea why some unvanted pixels are on the display?
Around the text it looks like clean.

https://www.dropbox.com/s/ljl9jrj557sofiz/Display.jpeg?dl=0

EDIT: Invert mode has 7 extra lines after Fill display.

https://www.dropbox.com/s/njihbj1jj3luuix/DisplayInvert.jpeg?dl=0

Br, Zsolt

**Comment by kuzmanzs** [comment]
I try to understand your code. For me it is unclear how image buffer works.
You have created 8 pages, 128 x 8 pixel pro pages.
Image buffer has a size of 1024 (128x8). 
My questions is how can store whole content of display in 1024. It should be 128x64 -> 8k big array or?

**Comment by bitbank2** [comment]
The first image looks like you didn't call oledFill(0); before drawing on the display. When the display powers up, the memory contents are random.

The whole display is 1024 bytes because each pixel is a single bit. Each byte holds 8 pixels oriented vertically with the LSB (least significant bit) at the top. Please see the SSD1306 datasheet for more info.

**Comment by kuzmanzs** [comment]
Thanks for the imagebuffer explanation.

Regarding https://www.dropbox.com/s/ljl9jrj557sofiz/Display.jpeg?dl=0
I am using your example with ch341 converter. It looks like when I CH341 use it do not has any effect if I call oledFill. Previous image/display won't erased. It can be HW issue? But the text are drawn.

Regarding https://www.dropbox.com/s/njihbj1jj3luuix/DisplayInvert.jpeg?dl=0
I am using it with your example, only in inverted mode.
i=oledInit(1, 0x3c, 1, 0);
oledFill(1); 
printf("Press ENTER to next\n");
getchar();

**Comment by bitbank2** [comment]
How are you using a CH341? Is this on a Raspberry Pi or are you using a USB to I2C converter for a different Linux machine?

**Comment by kuzmanzs** [comment]
I have two test setup.

one) Ubuntu 18 + CH341 on PC
two) RPI native

**Comment by bitbank2** [comment]
I'm not sure why you're seeing a problem with clearing the display memory. There are many variations of the display and they all seem to behave properly with my library.

**Comment by kuzmanzs** [comment]
I will test it, maybe CH341 causing problem, but it is interesting that with characters it is working well.

Could you test invert mode? I have unvanted 7 lines (white) on the display (RPI no CH341).
https://www.dropbox.com/s/njihbj1jj3luuix/DisplayInvert.jpeg?dl=0
