### ISSUE TITLE
How to change display size linux

### ISSUE THREAD

**Issue by DarkElvenAngel** [bitbank2/oled_96#6]
Hello,

I have tested your library and was trying to see how to change the display size from 128x64 to 128x32.  I'be only just received my oled display today and when I ran the sample code only the big text is readable.
The rest is to compressed to read.

Thanks

**Comment by bitbank2** [comment]
The different SSD1306 display sizes need slightly different initialization sequences. I'm working on adding support to the Linux code and will have it ready shortly.

**Comment by DarkElvenAngel** [comment]
This works great, Thanks.
