### ISSUE TITLE
Font change

### ISSUE THREAD

**Issue by kuzmanzs** [bitbank2/oled_96#7]
Hi,

I would like to change font type to Adafruit_GFX Glyph types.
I have checked your font library. How did you created your font lib? 
Do you any idea how can I use gfx fonts?

**Comment by bitbank2** [comment]
The fonts I use are simplistic bitmaps, not really 'Glyphs'. I got the 8x8 from IBM's original PC monochrome display and then stretched and smoothed them manually. You're welcome to add code to oled_96 and do a pull request, but I don't have time at the moment to rewrite the way the fonts are handled.
