### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by kr105** [bitbank2/oled_96#8]
Hello Larry,

I would like to start a derivative project based on this code but I can't find a reference on what license is this code released on. Can you please set a license? I highly recommend MIT but of course you are free to choose.

Thanks.-

**Comment by bitbank2** [comment]
I added the Apache 2.0 license. This should give you the freedom to use it as you like.
If you appreciate the code, please consider becoming a Github sponsor.

Thanks,
Larry B.
